# Generated by Django 5.2.14 on 2026-05-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_branding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/settings/logos/')),
                ('primary_color', models.CharField(default='#00E5FF', max_length=20)),
                ('secondary_color', models.CharField(default='#081028', max_length=20)),
                ('iva_percentage', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('tip_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('currency', models.CharField(default='COP', max_length=10)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('kitchen_printer_name', models.CharField(blank=True, max_length=120)),
                ('cashier_printer_name', models.CharField(blank=True, max_length=120)),
                ('enable_qr_orders', models.BooleanField(default=True)),
                ('enable_tips', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='restaurants.restaurant')),
            ],
        ),
    ]
