# Generated by Django 5.2.10 on 2026-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='auto_print_cashier',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='auto_print_kitchen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='cashier_ticket_width',
            field=models.CharField(choices=[('58', '58mm'), ('80', '80mm')], default='80', max_length=2),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='enable_auto_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='kitchen_ticket_width',
            field=models.CharField(choices=[('58', '58mm'), ('80', '80mm')], default='80', max_length=2),
        ),
    ]
