# Generated by Django 5.2.14 on 2026-05-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_restaurant_remove_orderitem_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('PREPARING', 'Preparando'), ('READY', 'Lista'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20),
        ),
    ]
