# Generated by Django 5.2.14 on 2026-05-26 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('FREE', 'Libre'), ('OCCUPIED', 'Ocupada'), ('RESERVED', 'Reservada'), ('CLOSED', 'Cerrada')], default='FREE', max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
        ),
    ]
