# Generated by Django 5.2.14 on 2026-05-28 03:07

from django.db import migrations, models


def map_closed_tables(apps, schema_editor):
    RestaurantTable = apps.get_model('tables', 'RestaurantTable')
    RestaurantTable.objects.filter(status='CLOSED').update(status='PAYMENT_PENDING')


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(map_closed_tables, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='restauranttable',
            name='status',
            field=models.CharField(choices=[('FREE', 'Libre'), ('OCCUPIED', 'Ocupada'), ('RESERVED', 'Reservada'), ('PAYMENT_PENDING', 'Pago pendiente')], default='FREE', max_length=20),
        ),
    ]
