# Generated by Django 5.2.10 on 2026-06-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_restauranttable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='type',
            field=models.CharField(choices=[('SALON', 'Salón'), ('TERRACE', 'Terraza'), ('VIP', 'VIP'), ('BAR', 'Barra')], default='SALON', max_length=20),
        ),
    ]
