# Generated by Django 5.2.10 on 2026-06-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_cashregistersession_total_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregistersession',
            name='counted_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashregistersession',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashregistersession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashregistersession',
            name='total_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashregistersession',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashregistersession',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashregistersession',
            name='total_qr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING', 'Apertura'), ('SALE', 'Venta'), ('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso'), ('TIP', 'Propina'), ('ADJUSTMENT', 'Ajuste'), ('CLOSING', 'Cierre'), ('ORDER_PAYMENT', 'Pago orden')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('DIGITAL', 'QR'), ('MIXED', 'Mixto'), ('OTHER', 'Otro')], default='CASH', max_length=20),
        ),
    ]
